# yaml-language-server: $schema=https://json.schemastore.org/github-action

name: 'Azure Static Web Apps Deploy'
description: 'Deploys an application to Azure Static Web Apps'
author: 'Microsoft'
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  action:
    description: 'Action to perform'
    required: true
    default: 'deploy'
  app_location:
    description: 'Directory location of the application source code'
    required: true
    default: './'
  azure_static_web_apps_api_token:
    description: 'Deploy token for Azure Static Web App'
    required: true
  repo_token:
    description: >
      Token for interacting with the Github repository which is currently used primarily
      for commenting on Pull Requests.

      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.

      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  skip_deploy_on_missing_secrets:
    description: 'Skip deployment if secrets are missing'
    default: 'true'
  api_build_command:
    description: 'Custom command for Oryx to run when building Azure Functions source code'
  api_location:
    description: 'Directory location of the Azure Functions source code'
  data_api_location:
    description: 'Directory location of the Data API configuration files'
  app_artifact_location:
    description: 'Identical in use to output_location'
  output_location:
    description: 'Directory location of the compiled application code after building'
  app_build_command:
    description: 'Custom command for Oryx to run when building application source code'
  routes_location:
    description: 'Directory location where the routes.json file can be found in the source code'
  skip_app_build:
    description: 'Skips the build step for the application source code if set to true.'
  config_file_location:
    description: 'Directory location where the staticwebapp.config.json file can be found in the source code'
  skip_api_build:
    description: 'Skips the build step for the Azure Functions source code if set to true.'
  production_branch:
    description: 'When specified, deployments from other branches will be considered preview environments.'
  deployment_environment:
    description: 'Name of the Azure Static Web Apps environment to deploy to.'
  is_static_export:
    description: 'Indicates you are using `next export` to generate a static site if set to true.'

outputs:
  static_web_app_url:
    description: 'Url of the application'
    value: ''

  image_name:
    description: 'Name of the Docker image used to run the action'
    value: ''

runs:
  using: 'composite'
  steps:
    - name: Set globals
      id: globals
      shell: bash
      env:
        RAW_GITHUB_ACTOR: ${{ github.actor }}
        RAW_GITHUB_REPOSITORY: ${{ github.action_repository || github.repository }}
        RAW_GITHUB_WORKSPACE: ${{ github.workspace }}

        RAW_INPUTS_REPO_TOKEN: ${{ inputs.repo_token }}
        RAW_INPUTS_APP_LOCATION: ${{ inputs.app_location }}
        RAW_INPUTS_APP_ARTIFACT_LOCATION: ${{ inputs.app_artifact_location }}
        RAW_INPUTS_DATA_API_LOCATION: ${{ inputs.app_artifact_location }}
        RAW_INPUTS_ACTION: ${{ inputs.action || 'deploy' }}
        RAW_INPUTS_AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ inputs.azure_static_web_apps_api_token || 'no_token_provided' }}
        RAW_INPUTS_SKIP_DEPLOY_ON_MISSING_SECRETS: ${{ inputs.skip_deploy_on_missing_secrets == 'true' && '--skipDeployOnMissingSecrets'|| null }}
        RAW_INPUTS_SKIP_APP_BUILD: ${{ inputs.skip_app_build == 'true' && '--skipAppBuild' || null }}
      run: |
        function write_env() {
          set -ea -o pipefail

          echo "TA_USERNAME=$RAW_GITHUB_ACTOR"
          echo "TA_PASSWORD=$RAW_INPUTS_REPO_TOKEN"
          echo "TA_TOKEN=$RAW_INPUTS_REPO_TOKEN"

          local RAW_GITHUB_REPOSITORY="${RAW_GITHUB_REPOSITORY:-joelvaneenwyk/static-web-apps-deploy:develop}"
          echo "TA_REPOSITORY=$RAW_GITHUB_REPOSITORY"
          echo "TA_GHCR_IMAGE=ghcr.io/$RAW_GITHUB_REPOSITORY"

          local RAW_INPUTS_APP_LOCATION="${RAW_INPUTS_APP_LOCATION:-}"
          RAW_INPUTS_APP_LOCATION="${RAW_INPUTS_APP_LOCATION#./}"
          if [[ "$RAW_INPUTS_APP_LOCATION" == "." ]]; then
            RAW_INPUTS_APP_LOCATION=""
          else
            RAW_INPUTS_APP_LOCATION="${RAW_INPUTS_APP_LOCATION#.}"
          fi

          local TA_WORKSPACE_LOCAL_PATH="${RAW_GITHUB_WORKSPACE:-}/$RAW_INPUTS_APP_LOCATION"
          TA_WORKSPACE_LOCAL_PATH="${TA_WORKSPACE_LOCAL_PATH%/}"
          echo "TA_WORKSPACE_LOCAL_PATH=$TA_WORKSPACE_LOCAL_PATH"

          local TA_WORKSPACE_DOCKER_PATH="/workspace/$RAW_INPUTS_APP_LOCATION"
          TA_WORKSPACE_DOCKER_PATH="${TA_WORKSPACE_DOCKER_PATH%/}"
          echo "TA_WORKSPACE_DOCKER_PATH=$TA_WORKSPACE_DOCKER_PATH"

          local RAW_INPUTS_APP_ARTIFACT_LOCATION="${RAW_INPUTS_APP_ARTIFACT_LOCATION:-}"
          RAW_INPUTS_APP_ARTIFACT_LOCATION="${RAW_INPUTS_APP_ARTIFACT_LOCATION#./}"
          local TA_DATA_APP_ARTIFACT_LOCATION="$TA_WORKSPACE_DOCKER_PATH/$RAW_INPUTS_APP_ARTIFACT_LOCATION"
          TA_DATA_APP_ARTIFACT_LOCATION="${TA_DATA_APP_ARTIFACT_LOCATION%/}"

          local RAW_INPUTS_DATA_API_LOCATION="${RAW_INPUTS_DATA_API_LOCATION:-}"
          RAW_INPUTS_DATA_API_LOCATION="${RAW_INPUTS_DATA_API_LOCATION#./}"
          local TA_DATA_API_LOCATION="$TA_WORKSPACE_DOCKER_PATH/$RAW_INPUTS_DATA_API_LOCATION"
          TA_DATA_API_LOCATION="${TA_DATA_API_LOCATION%/}"

          echo "TA_CLI_INPUT_ACTION=${RAW_INPUTS_ACTION:-deploy}"
          echo "TA_CLI_APP_LOCATION=--app $TA_WORKSPACE_DOCKER_PATH"
          echo "TA_CLI_DATA_APP_ARTIFACT_LOCATION=--appArtifactLocation $TA_DATA_APP_ARTIFACT_LOCATION"
          echo "TA_CLI_DATA_API_LOCATION=--api $TA_DATA_API_LOCATION"
          echo "TA_CLI_AZURE_STATIC_WEB_APPS_API_TOKEN=--apiToken ${RAW_INPUTS_AZURE_STATIC_WEB_APPS_API_TOKEN:-invalid_default_token}"
          echo "TA_CLI_SKIP_DEPLOY_ON_MISSING_SECRETS=$RAW_INPUTS_SKIP_DEPLOY_ON_MISSING_SECRETS"
          echo "TA_CLI_SKIP_APP_BUILD=$RAW_INPUTS_SKIP_APP_BUILD"
        }
        write_env | tee -a "${GITHUB_OUTPUT:-./.env.action_output}"

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ steps.globals.outputs.TA_USERNAME }}
        password: ${{ steps.globals.outputs.TA_PASSWORD }}
        logout: false

    - name: Extract Image Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.globals.outputs.TA_GHCR_IMAGE }}

    - name: Build Image
      id: docker-push
      uses: docker/build-push-action@v6
      with:
        context: ${{ github.action_path }}
        file: ${{ github.action_path }}/Dockerfile
        push: false
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Get Image Name
      id: get-image-name
      shell: bash
      env:
        DEFAULT_IMAGE_NAME: 'ghcr.io/joelvaneenwyk/static-web-apps-deploy:develop'
        IMAGE_NAME: ${{ steps.docker-push.outputs.metadata && fromJSON(steps.docker-push.outputs.metadata)['image.name'] }}
      run: echo "image_name="${IMAGE_NAME:-${DEFAULT_IMAGE_NAME}}"" >> $GITHUB_OUTPUT

    - name: Run
      shell: bash
      env:
        WORKSPACE_LOCAL_PATH: '${{ steps.globals.outputs.TA_WORKSPACE_PATH }}'
        WORKSPACE_DOCKER_PATH: '${{ steps.globals.outputs.TA_WORKSPACE_PATH }}'
        DOCKER_IMAGE: '${{ steps.get-image-name.outputs.image_name }}'
        CLI_ARGS: >-
          ${{ steps.globals.outputs.TA_CLI_AZURE_STATIC_WEB_APPS_API_TOKEN }}
          ${{ steps.globals.outputs.TA_CLI_APP_LOCATION }}
          ${{ steps.globals.outputs.TA_CLI_DATA_APP_ARTIFACT_LOCATION }}
          ${{ steps.globals.outputs.TA_CLI_DATA_API_LOCATION }}
          ${{ steps.globals.outputs.TA_CLI_SKIP_DEPLOY_ON_MISSING_SECRETS }}
          ${{ steps.globals.outputs.TA_CLI_SKIP_APP_BUILD }}
          ${{ steps.globals.outputs.TA_CLI_INPUT_ACTION }}
      run: >-
        docker run --rm
        -v "$WORKSPACE_LOCAL_PATH":"$WORKSPACE_DOCKER_PATH"
        -v "$WORKSPACE_LOCAL_PATH/.git":"$WORKSPACE_DOCKER_PATH/.git":ro
        --workdir "$WORKSPACE_DOCKER_PATH"
        "$DOCKER_IMAGE"
        $CLI_ARGS
