#
# static-web-apps-deploy
#

services:
  static-web-apps-deploy:
    build:
      context: .
      dockerfile: "Dockerfile"
    env_file:
      - .env
    volumes:
      - .:/github/workspace
    environment:
      SKIP_DEPLOY_ON_MISSING_SECRETS: true
      ACTIONS_CACHE_URL:
      ACTIONS_ID_TOKEN_REQUEST_TOKEN:
      ACTIONS_ID_TOKEN_REQUEST_URL:
      ACTIONS_RESULTS_URL:
      ACTIONS_RUNTIME_TOKEN:
      ACTIONS_RUNTIME_URL:
      APP_LOCATION: ""
      AZURE_STATIC_WEB_APPS_API_TOKEN: ""
      CI: true
      DART_SASS_SHA_LINUX:
      DART_SASS_SHA_MACOS:
      DART_SASS_SHA_WINDOWS:
      GITHUB_ACTION_REF:
      GITHUB_ACTION_REPOSITORY:
      GITHUB_ACTION:
      GITHUB_ACTIONS: true
      GITHUB_ACTOR_ID:
      GITHUB_ACTOR:
      GITHUB_API_URL:
      GITHUB_BASE_REF:
      GITHUB_ENV:
      GITHUB_EVENT_NAME:
      GITHUB_EVENT_PATH:
      GITHUB_GRAPHQL_URL:
      GITHUB_HEAD_REF:
      GITHUB_JOB:
      GITHUB_OUTPUT:
      GITHUB_PATH:
      GITHUB_REF_NAME:
      GITHUB_REF_PROTECTED:
      GITHUB_REF_TYPE:
      GITHUB_REF:
      GITHUB_REPOSITORY_ID:
      GITHUB_REPOSITORY_OWNER_ID:
      GITHUB_REPOSITORY_OWNER:
      GITHUB_REPOSITORY:
      GITHUB_RETENTION_DAYS:
      GITHUB_RUN_ATTEMPT:
      GITHUB_RUN_ID:
      GITHUB_RUN_NUMBER:
      GITHUB_SERVER_URL:
      GITHUB_SHA:
      GITHUB_STATE:
      GITHUB_STEP_SUMMARY:
      GITHUB_TRIGGERING_ACTOR:
      GITHUB_WORKFLOW_REF:
      GITHUB_WORKFLOW_SHA:
      GITHUB_WORKFLOW:
      GITHUB_WORKSPACE:
      GO111MODULE:
      GOPROXY:
      HOME:
      INPUT_ACTION:
      INPUT_API_BUILD_COMMAND:
      INPUT_API_LOCATION:
      INPUT_APP_ARTIFACT_LOCATION:
      INPUT_APP_BUILD_COMMAND:
      INPUT_APP_LOCATION:
      INPUT_AZURE_STATIC_WEB_APPS_API_TOKEN:
      INPUT_CONFIG_FILE_LOCATION:
      INPUT_DATA_API_LOCATION:
      INPUT_DEPLOYMENT_ENVIRONMENT:
      INPUT_IS_STATIC_EXPORT:
      INPUT_OUTPUT_LOCATION:
      INPUT_PRODUCTION_BRANCH:
      INPUT_REPO_TOKEN:
      INPUT_ROUTES_LOCATION:
      INPUT_SKIP_API_BUILD:
      INPUT_SKIP_APP_BUILD:
      LD_LIBRARY_PATH:
      PKG_CONFIG_PATH:
      Python_ROOT_DIR:
      Python2_ROOT_DIR:
      Python3_ROOT_DIR:
      pythonLocation:
      RUNNER_ARCH:
      RUNNER_ENVIRONMENT:
      RUNNER_NAME:
      RUNNER_OS:
      RUNNER_TEMP:
      RUNNER_TOOL_CACHE:
      RUNNER_WORKSPACE:
      SASS_VERSION:
      STATIC_API_LOCATION:
      STATIC_APP_LOCATION:
      STATIC_OUTPUT_LOCATION:
