[build.environment]
DART_SASS_VERSION = "1.70.0"
HUGO_VERSION = "0.122.0"
HUGO_ENV = "production"
HUGO_BASEURL = "https://static-web-apps-deploy.netlify.app"

[build]
publish = "test/public"
command = "npm install && npm run build"
