name: Validate Github Action

on:
  push:
    branches: [main, develop, feature/**]
  pull_request:
    branches: [main, develop, feature/**]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./
        name: Test
        with:
          action: build
          app_location: ./test
          output_location: ./test/public
          repo_token: ${{ github.token }}
          skip_deploy_on_missing_secrets: true
        env:
          HUGO_VERSION: 0.122.0
          SASS_VERSION: 1.70.0
