name: Build GitHub Action

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    outputs:
      image_name: ${{ steps.get-build-name.outputs.image_name }}

    name: Build Docker Image
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Container Registry
        uses: docker/login-action@3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Image Metadata
        id: meta
        uses: docker/metadata-action@5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and Push Image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: '${{ github.workspace }}'
          file: '${{ github.workspace }}/Dockerfile'
          push: true
          load: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: get-build-name
        name: Get Image Name
        run: |
          imageName=${{ fromJSON(steps.push.outputs.metadata)['image.name'] }}
          echo "::set-output name=image_name::$imageName"

  # Inspired by the following example:
  #
  #   - https://github.com/docker/build-push-action/issues/614#issuecomment-1130396065
  validate-docker-image:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    name: Validate Docker Image
    steps:
      - name: Login Container Registry
        uses: docker/login-action@3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test 'version' Command
        run: |
          echo "Checking image..."
          docker run --rm ${{needs.build-and-push-image.outputs.image_name}} version

  build:
    needs: validate-docker-image
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: '${{ matrix.os }}'
    name: 'Build Local Action'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        env:
          NONINTERACTIVE: 1

      - name: Setup Hugo
        run: |
          brew install hugo
          hugo version

      - name: Setup Embedded Dart Sass
        run: |
          brew install sass/sass/sass
          sass --embedded --version

      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./
        name: Test
        with:
          action: build
          app_location: ./test
          output_location: ./test/public
          repo_token: ${{ github.token }}
          skip_deploy_on_missing_secrets: true
