name: Build GitHub Action

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: '${{ matrix.os }}'
    name: 'Build Local Action'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
        env:
          NONINTERACTIVE: 1

      - name: Setup Hugo
        run: |
          brew install hugo
          hugo version

      - name: Setup Embedded Dart Sass
        run: |
          brew install sass/sass/sass
          sass --embedded --version

      - run: npm install
      - run: npm run build

  docker-build:
    needs: build
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3.0.0
        env:
          DOCKER_BUILDKIT: '1'
        with:
          buildkitd-flags: --debug
          cleanup: false

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: static-web-apps-deploy:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false

      - name: Run
        uses: addnab/docker-run-action@v3
        env:
          SKIP_DEPLOY_ON_MISSING_SECRETS: true
        with:
          image: static-web-apps-deploy:latest
          run: >-
            build
            --skipAppBuild false
            --app ./test
            --apiToken "invalid_token"

  test:
    needs: build
    runs-on: ubuntu-latest
    name: Test GitHub Action
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: ./
        name: Test
        with:
          action: build
          app_location: ./test
          output_location: ./test/public
          repo_token: ${{ github.token }}
          skip_deploy_on_missing_secrets: true
